### ISSUE TITLE
Failure with workspaces with slashes in their names

### ISSUE THREAD

**Issue by cadadr** [JonnyHaystack/i3-resurrect#54]
**Describe the bug**
My workspaces are as follows: `1/home`, `2/www`, `3/rsc`.  This causes a `FileNotFoundError` because the slash in the name is interpreted as a directory separator.

**To Reproduce**
Run `i3-resurrect -w '1/home'`

**Expected behavior**
Work w/o problems, using a slug for the filename.

**System information (please complete the following information):**
 - Linux distribution: Debian Testing
 - i3-resurrect version (output of `i3-resurrect --version`): i3-resurrect, version 1.3.2
 - i3 version (output of `i3 -v`): i3 version 4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
 - Python version (output of `python -V`): Python 3.7.5

**Additional context**
Traceback:

```
Traceback (most recent call last):
  File "/home/g/.local/bin/i3-resurrect", line 10, in <module>
    sys.exit(main())
  File "/home/g/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/g/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/g/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/g/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/g/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/g/.local/lib/python3.7/site-packages/i3_resurrect/main.py", line 54, in save_workspace
    save_layout(workspace, directory, swallow_criteria)
  File "/home/g/.local/lib/python3.7/site-packages/i3_resurrect/main.py", line 69, in save_layout
    with layout_file.open('w') as f:
  File "/usr/lib/python3.7/pathlib.py", line 1193, in open
    opener=self._opener)
  File "/usr/lib/python3.7/pathlib.py", line 1046, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/g/.i3/i3-resurrect/workspace_1/home_layout.json'
```

**Comment by cedl38** [comment]
As a workaround, you can try the next branch with --numeric option and this pull request #53 to restore name.

**Comment by JonnyHaystack** [comment]
Thanks for the issue, I will probably just sanitise the forward slash to some other character and then @cedl38's PR should handle restoring the name correctly. I'll get on both of those when I have time.
