### ISSUE TITLE
Getting  Could not connect to i3 on socket error on Save

### ISSUE THREAD

**Issue by yar00001** [JonnyHaystack/i3-resurrect#99]
**Describe the bug**
Cannot save the workspace

**To Reproduce**
- `i3-resurrect save -w '4: Code'`

**Expected behavior**
- ws should be saved

**System information (please complete the following information):**
 - Linux distribution: 
 - i3-resurrect version (output of `i3-resurrect --version`):  i3-resurrect, version 1.4.3
 - i3 version (output of `i3 -v`):  i3 version 4.18.2 (2020-07-26) © 2009 Michael Stapelberg and contributors
 - Python version (output of `python -V`): Python 3.8.5

**Additional context**
error message:
```
❯ i3-resurrect save -w '4: Code'
i3-msg: Could not connect to i3 on socket /run/user/627900527/i3/ipc-socket.5367: No such file or directory
Traceback (most recent call last):
  File "/home/ANT.AMAZON.COM/yarhooma/.local/bin/i3-resurrect", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ANT.AMAZON.COM/yarhooma/.local/lib/python3.8/site-packages/i3_resurrect/main.py", line 62, in save_workspace
    layout.save(workspace, numeric, directory, profile, swallow_criteria)
  File "/home/ANT.AMAZON.COM/yarhooma/.local/lib/python3.8/site-packages/i3_resurrect/layout.py", line 24, in save
    workspace_tree = treeutils.get_workspace_tree(workspace, numeric)
  File "/home/ANT.AMAZON.COM/yarhooma/.local/lib/python3.8/site-packages/i3_resurrect/treeutils.py", line 84, in get_workspace_tree
    subprocess.check_output(shlex.split('i3-msg -t get_tree'))
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['i3-msg', '-t', 'get_tree']' returned non-zero exit status 1.

```

**Comment by JonnyHaystack** [comment]
Seems like something's wrong with your i3. The IPC socket isn't working. Have you tried a restart?

**Comment by yar00001** [comment]
Yes it seems this is a fault from my i3 and not i3-resurrect. I could make this work by restarting i3.
